events {}

http {

    upstream shop_backend {
        least_conn;
        server app:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://shop_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}