spring:
  cloud:
    openfeign:
      client:
        config:
          deliveryApi:
            url: ${DELIVERY_API_URL}
            connect-timeout: 1000
            read-timeout: 3000
  application:
    name: ecommerce-assignment
  datasource:
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 1000ms

resilience4j:
  circuitbreaker:
    instances:
      deliveryApi:
        sliding-window-size: 10
        failure-rate-threshold: 50        # 50% 실패 시 OPEN
        wait-duration-in-open-state: 10s  # 10초 후 HALF_OPEN
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
          - java.net.UnknownHostException
          - java.net.SocketTimeoutException
          - feign.RetryableException
  retry:
    instances:
      deliveryApi:
        max-attempts: 3                   # 최대 3번 시도
        wait-duration: 1s                 # 초기 대기 1초
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 3 # 1초 → 3초 → 9초
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
          - java.net.UnknownHostException
          - java.net.SocketTimeoutException
          - feign.RetryableException
        ignore-exceptions:
          - com.example.ecommerceassignment.exception.DeliveryBadRequestException

order:
  queue:
    name: order.pending
    exchange: order.exchange
    routing-key: order.pending
  confirmed:
    queue: order.confirmed
    exchange: order.confirmed.exchange
    routing-key: order.confirmed