services:
  shop-mysql:
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
    container_name: shop-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --innodb_buffer_pool_size=512M
      --innodb_flush_log_at_trx_commit=1
      --innodb_lock_wait_timeout=5
      --max_connections=300
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    tmpfs:
      - '/var/lib/mysql'
    networks:
      - shop-network

  shop-redis:
    image: redis:7.2-alpine
    container_name: shop-redis
    ports:
      - "6379:6379"
    volumes:
      - /data
    command: redis-server --appendonly no --save "" --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - shop-network

  shop-rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: shop-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    tmpfs:
      - /var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-network

  app:
    image: shop-app:latest
    restart: always
    depends_on:
      shop-mysql:
        condition: service_healthy
      shop-redis:
        condition: service_healthy
      shop-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://shop-mysql:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: shop
      SPRING_DATASOURCE_PASSWORD: shop
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: shop-redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: shop-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    networks:
      - shop-network

  nginx:
    image: nginx:latest
    container_name: shop-nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shop-network

  locust:
    image: locustio/locust
    container_name: locust
    environment:
      TEST_MODE: preoccupy
    depends_on:
      - app
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: >
      -f /mnt/locust/locustfile.py
      --host http://nginx
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge